[build]

# Pi 0/1
[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

# Pi 2/3/4
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-none-linux-gnueabihf-gcc"

# (Optional) Set default target for cargo build
# target = "armv7-unknown-linux-gnueabihf"
# rustflags = ["-C", "linker=arm-none-linux-gnueabihf-gcc"]

[target.arm-unknown-linux-musleabi]
linker = "arm-linux-gnueabihf-ld"

[target.x86_64-linux-musleabi]
linker = "x86_64-linux-gnueabihf-ld"
